trigger:
- master

pool:
  name: Self-Hosted-Laptop
  demands: msbuild

resources:
  repositories:
  - repository: yourGitHubRepo  # The name for this repository resource
    type: github
    endpoint: githubconnection  # The name of your GitHub service connection in Azure DevOps
    name: sudhvihaan/Database1  # The GitHub repository name
    ref: master  # The branch you want to build

steps:
- task: MSBuild@1
  displayName: 'Build solution Database1.sln'
  inputs:
    solution: Database1.sln
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- powershell: |
    # List the contents of the artifact folder
    dir $(Build.ArtifactStagingDirectory)
  displayName: 'List Artifact Contents'

- powershell: |
    # Enable Query Store for the database
    $connectionString = "Server=tcp:sqlserver-db-name1.database.windows.net,1433;Initial Catalog=ivarusltd;Persist Security Info=False;User ID=admin123;Password={asda123$};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    
    $databaseName = "ivarusltd"
    Invoke-SqlCmd -ConnectionString $connectionString -Query "ALTER DATABASE [$databaseName] SET QUERY_STORE = ON"
  displayName: 'Enable Query Store'


- task: SqlAzureDacpacDeployment@1
  name: DeployingToDatabase
  displayName: 'Azure SQL DacpacTask'
  inputs:
    azureSubscription: 'ServiceConnection-to-Kaushik'
    ServerName: 'sqlserver-db-name1.database.windows.net'
    DatabaseName: ivarusltd
    SqlUsername: admin123
    SqlPassword: 'asda123$'
    #DacpacFile: '$(System.DefaultWorkingDirectory)/publishingtheartifact/drop/Database1.dacpac'
    DacpacFile: '$(Build.ArtifactStagingDirectory)/Database1.dacpac'



